# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ThreadingMaster
                                 A QGIS plugin
 A QGIS Plugin with threading
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-12-20
        copyright            : (C) 2018 by Alessandro Cristofori
        email                : alessandro.cristofori@halliburton.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ThreadingMaster class from file ThreadingMaster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .search.main import ThreadingMaster
    return ThreadingMaster(iface)
