# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ThreadingMaster
                                 A QGIS plugin
 A QGIS Plugin with threading
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-12-20
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Alessandro Cristofori
        email                : alessandro.cristofori@halliburton.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# Use pdb for debugging
import pdb
import tweepy
import datetime
import os.path
# import qgis.utils
from abc import abstractmethod
from sys import platform
from qgis.core import QgsProject, QgsWkbTypes, QgsVectorLayer 
# Initialize Qt resources from file resources.py
from .resources import *
from PyQt5.QtGui import QIcon, QColor, QDoubleValidator
from PyQt5.QtWidgets import QAction, QStyle, QApplication, \
    QMessageBox, QFileDialog
from PyQt5.QtCore import QObject, QSettings, QTranslator, qVersion, QCoreApplication, \
    pyqtSlot, pyqtRemoveInputHook, pyqtSignal
from .mod_tweepy import TweetsHandler, GeoStreamListener, \
    PlaceStreamListener, TweetsAuthHandler
from .tweet_layers import GeoTweetLayer, PlaceTweetLayer
from .layer_export import ShpLayerExport
from .gui_messages import *

# Import the code for the dialog
from .threading_master_dialog import ThreadingMasterDialog


class Signals(QObject):
    """General pyQtsignal class"""
    stream_on = pyqtSignal()


class ThreadingMaster:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'ThreadingMaster_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = ThreadingMasterDialog()
        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Threading Master')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'ThreadingMaster')
        self.toolbar.setObjectName(u'ThreadingMaster')
        self.app_name = (u'Qwitty')
        # get user OS ['darwin', 'linux', 'win32'] and home directory
        self.user_os = platform
        self.home_dir = os.path.expanduser('~')
        print("operating system is {0}".format(self.user_os))
        print("home dir is {0}".format(self.home_dir))
        # initialise tweepy classes
        self.tweets_handler = TweetsHandler()
        self.tweets_auth = TweetsAuthHandler()
        self.api_obj = self.tweets_auth.get_api_obj()
        # initialise user interactions
        self.setup_navigation()
        # initialise signals 
        self.signals = Signals()
        self.tweet_layer = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('ThreadingMaster', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/threading_master/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Threading Master'),
            callback=self.run,
            parent=self.iface.mainWindow())
    
    def setup_navigation(self):
        """ initialise all the users' interaction with the dialog window """
        # initialise dialog interactions
        self.dlg.stopButton.setIcon(QApplication.style().standardIcon(QStyle.SP_MediaPause))
        self.dlg.stopButton.setEnabled(False)
        self.dlg.saveLayerButton.setEnabled(False) # change it to false when finished debugging
        self.dlg.stopButton.clicked.connect(self.emit_stop)
        self.dlg.streamButton.clicked.connect(self.on_get_stream)
        self.dlg.saveLayerButton.clicked.connect(self.on_save_layer)
        self.dlg.streamButton.setIcon(QApplication.style().standardIcon(QStyle.SP_MediaPlay))
        self.dlg.SearchTypeDd.addItem("Tweet Location", "_geo_tweets")
        self.dlg.SearchTypeDd.addItem("User Place", "_place_tweets")
        self.dlg.limitDd.setEnabled(False)
        self.dlg.limitSb.setEnabled(False)
        self.dlg.limitCheckBox.stateChanged.connect(self.toggle_limits)
        self.dlg.XMinLineEdit.setValidator(QDoubleValidator(-90.0000, 90.0000, 4))
        self.dlg.YMinLineEdit.setValidator(QDoubleValidator(-180.0000, 180.0000, 4))
        self.dlg.XMaxLineEdit.setValidator(QDoubleValidator(-90.0000, 90.0000, 4))
        self.dlg.YMaxLineEdit.setValidator(QDoubleValidator(-180.0000, 180.0000, 4))
        

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Threading Master'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
        
    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            pass
  
    def toggle_limits(self):
        state = self.dlg.limitCheckBox.isChecked()
        self.dlg.limitDd.setEnabled(state)
        self.dlg.limitSb.setEnabled(state)
    
    def emit_stop(self):
        self.signals.stream_on.emit()
        self.dlg.stopButton.setEnabled(False)
        self.dlg.streamButton.setEnabled(True)
        self.dlg.saveLayerButton.setEnabled(True)
        self.tweet_layer = None

    def tweet_to_file(self, message):
        with open(os.path.join(self.home_dir, 'tweets_report.txt'), 'a+') as report:
            report.write(str(message))
    
    def tweet_to_layer(self, geo_tweet):
        print(str(geo_tweet))
        
        self.tweet_layer.add_tweet_feature(geo_tweet)
        self.tweet_layer.highlight_tweet_feature(geo_tweet, self.iface)
    
    def on_stream_error(self, status_error):
        print("there was an error in the stream, shut down")
        StreamErrorMessageBox(self.app_name, status_error)
        return False
    
    def on_save_layer(self):
        map_layers_names = [layer[1].name() for layer in QgsProject.instance().mapLayers().items()]
        if self.tweet_layer is not None and self.tweet_layer.name() in map_layers_names:
            file_name = QFileDialog.getSaveFileName(self.dlg, "Save File",
            os.path.join(self.home_dir, "{0}.{1}".format(self.tweet_layer.name(), "gpkg")),
            "Geopackage (*.gpkg);; Shapefile (*.shp)")
            print(file_name)
            if file_name[1] != '' and file_name[0] != '':
                shp_export = ShpLayerExport(self.tweet_layer, file_name[0])
                export_error = shp_export.export_layer()
                if export_error is None:
                    ExportSuccessMessageBox(self.app_name, self.tweet_layer.name())
                else:
                    ExportFailMessageBox(self.app_name, self.tweet_layer.name(), export_error)
            else:
                return
        else:
            UndefinedMessageBox(self.app_name, "Tweet Layer")

    
    def add_tweet_layer(self, src_type, src_kw):
        """ 
        Add the in-memory tweets layer to the map canvas 
        :param src_type: string
        :param src_kw: string
        """
        map_layers = [layer[1] for layer in QgsProject.instance().mapLayers().items()
        if type(layer[1]) == GeoTweetLayer or type(layer[1]) == PlaceTweetLayer]
        for layer in map_layers:
            if layer.name() == "{0}{1}".format(src_kw, src_type) and \
            layer.providerType() == 'memory' and \
            layer.wkbType() == QgsWkbTypes.Point:
                self.tweet_layer = layer
        if self.tweet_layer is None:
            if src_type == "_geo_tweets":
                self.tweet_layer = GeoTweetLayer("EPSG:4326", src_kw)
            else:
                self.tweet_layer = PlaceTweetLayer("EPSG:4326", src_kw)
            QgsProject.instance().addMapLayer(self.tweet_layer)
        
    def activate_stream(self, src_type, src_kw):
        if src_type == "_geo_tweets":
            stream_listener = GeoStreamListener(self.tweet_to_layer, 
            self.signals.stream_on,
            self.tweet_to_file,
            self.on_stream_error,
            api=self.api_obj)
        else:
            stream_listener = PlaceStreamListener(
            self.tweet_to_layer, 
            self.signals.stream_on,
            self.tweet_to_file,
            self.on_stream_error,
            api=self.api_obj)
        myStream = tweepy.Stream(auth=self.api_obj.auth, listener=stream_listener)
        myStream.filter(track=src_kw, is_async=True)

    def on_get_stream(self):
        """Test Tweet Streamer"""
        keywords = self.dlg.streamLineEdit.text().split()
        if len(keywords) == 0: 
            print("no text found")
        else:
            self.dlg.streamButton.setEnabled(False)
            self.dlg.stopButton.setEnabled(True)
            if self.dlg.saveLayerButton.isEnabled():
                self.dlg.saveLayerButton.setEnabled(False)
            search_type = self.dlg.SearchTypeDd.itemData(self.dlg.SearchTypeDd.currentIndex())
            self.add_tweet_layer(search_type, "_".join(keywords))
            self.activate_stream(search_type, keywords)
